import React from 'react'

export default function page() {
  return (
    <section class="py-20"><div class="container mx-auto px-4"><div class="max-w-4xl mx-auto mb-16"><h2 class="mb-10 text-red-500 text-2xl lg:text-3xl font-bold font-heading text-center border-b-2 border-gray-100">Pre-Foundation Course (For Students of Class VIII, IX &amp; X)</h2> <h3 class=" text-2xl leading-8 font-extrabold text-gray-900 sm:text-3xl sm:leading-9 dark:text-white">
                Pre-Foundation
            </h3> <p class="mt-3 text-base leading-6 text-gray-500 dark:text-gray-200 text-justify">
                Apex Classes strongly believes in developing the inquisitiveness and curiosity of children into logical thinking. Foundation Builder is the first step towards nurturing the young minds of the country. The proficiency in Science and Math lies on the clarity of thoughts. Hence, we attempt to inculcate these concepts with absolute clarity and lucidity. Students get an opportunity to learn these subjects from expert and experienced faculties, who make these subjects more interesting and very easy to understand. Moreover, learning becomes a delightful experience here due to modern teaching methodology. We help our students to think out-of-the-box; a skill that is indispensable to succeed at competitive examinations in future. 
            </p> <h3 class="mt-6 text-2xl leading-8 font-extrabold text-gray-900 sm:text-3xl sm:leading-9 dark:text-white">
                Importance of the Foundation Course
            </h3> <p class="mt-3 text-base leading-6 text-gray-500 dark:text-gray-200 text-justify">
               Preparing with Foundation Course helps identify scholastic talent in students. Trying to identify their skill level earlier is does not mean putting pressure on a student to suddenly turn into a prodigy. Aptitude needs learning and practice to reach its full potential. Preparing for competitive exams is about helping your child to achieve the best he can. 
            </p> <h3 class="mt-6 text-2xl leading-8 font-extrabold text-gray-900 sm:text-3xl sm:leading-9 dark:text-white">
                INTERNATIONAL OLYMPIADS
            </h3> <p class="mt-3 text-base leading-6 text-gray-500 dark:text-gray-200 text-justify">Olympiads are internationally recognized competitions in various fields of Science. They are the highest level thinking examinations and are hosted by different countries every year. Participation in any of the Olympiads is worldwide recognized and is considered as a great achievement. International Olympiads are held every year in Mathematics, Physics, Chemistry, Biology, Astronomy and Junior Science. 

</p> <p class="mt-3 text-base leading-6 text-gray-500 dark:text-gray-200 text-justify">Apex has attained an exalted prestige producing the best results at Olympiads (Physics, Chemistry, Mathematics, Astronomy &amp; Biology) Year-after-year. The fact that these Olympiads are held internationally and, our students are successful in them consistently, is a testimony to our high standard of teaching &amp; impeccable quality of teachers.</p> <h3 class="mt-6 text-2xl leading-8 font-extrabold text-gray-900 sm:text-3xl sm:leading-9 dark:text-white">
                ABOUT INTERNATIONAL OLYMPIADS
            </h3> <p class="mt-3 text-base leading-6 text-gray-500 dark:text-gray-200 text-justify">
                The International Olympiad(10)programme follows a five stage process All the subsequent stages are conducted by Homi Bhabha Centre for Science Education(HBCSE), Mumbai (www.hbcse.tif.res.in)
            </p></div> <div class="flex flex-wrap mt-16 mx-4 -mb-8"><div class="w-full lg:w-1/5 px-2"><div class="h-full p-8 bg-white border rounded shadow-lg transform transition duration-500 hover:scale-105"><div class="mb-6 flex items-start"><h3 class="text-xl font-bold text-center text-red-600">National Standard Examinations (NSEs)</h3></div> <p> Physics, Chemistry, Biology, Astronomy organized by IAPT.</p></div></div> <div class="w-full lg:w-1/5 px-2 "><div class="h-full p-8 bg-white border rounded shadow-lg transform transition duration-500 hover:scale-105"><div class="mb-6 flex items-start"><h3 class="text-xl font-bold text-center text-red-600">Indian National Olympiad (INO) examination</h3></div> <p> The eligible students from stage one can participate In INO in respective subjects . </p></div></div> <div class="w-full lg:w-1/5 px-2 "><div class="h-full p-8 bg-white border rounded shadow-lg transform transition duration-500 hover:scale-105"><div class="mb-6 flex items-start"><h3 class="text-xl font-bold text-center text-red-600">Orientation-Cum-Selection Camps (OCSC)</h3></div> <p> For these camps, about 35 students in each subject will be selected from INO on performance basis.</p></div></div> <div class="w-full lg:w-1/5 px-2 "><div class="h-full p-8 bg-white border rounded shadow-lg transform transition duration-500 hover:scale-105"><div class="mb-6 flex items-start"><h3 class="text-xl font-bold text-center text-red-600">Pre Departure Training (PDT)</h3></div> <p> These students will have a Pre- Departure Training (PDT) for two weeks.</p></div></div> <div class="w-full lg:w-1/5 px-2 "><div class="h-full p-8 bg-white border rounded shadow-lg transform transition duration-500 hover:scale-105"><div class="mb-6 flex items-start"><h3 class="text-xl font-bold text-center text-red-600">International Olympiad (IO)</h3></div> <p>Participation in International Olympiad (I0) of the selected students</p></div></div></div></div></section>
  )
}
